
Import('env')

env.Append(CCFLAGS=["/std:c++20", "/EHsc"])

source_files = [
    'arrow_functions.cpp',
    'arrow.cpp',
    'main.cpp',
    'point_functions.cpp',
    'triangle.cpp'
]
exec = env.Program(target='hello_classes_project', source=source_files)
Default(exec)
