
Import('env')

env.Append(CCFLAGS=["/std:c++20", "/EHsc"])

# Executing SConscript files nested in the source tree, it could be more than one.
SConscript([
    'arrow_lib/SConscript'
], 'env')

# Custom environment to build the executable
env_exe = env.Clone()

# Telling our environment ...
env_exe.Append(
    # where are the includes for the arrow_library
    CPPPATH=['arrow_lib/include'],

    # where to find libraries
    LIBPATH=['arrow_lib'],

    # the name of the required libraries
    LIBS=['arrow_library']
)

exec = env_exe.Program(target='shared_lib_demo_ws', source=['main.cpp'])
Default(exec)
